#!/usr/bin/env python3
"""Generate src/font8x16.h from a PSF1/PSF2 console font.

Default source is Terminus Bold 16 (SIL OFL 1.1), a hand-designed bitmap font
that stays crisp at 8x16 with no antialiasing to throw away. The bold cut is
deliberate: the screen is read at arm's length and the renderer draws every
glyph as-is. Thickening a light face in software -- smearing each stroke a
pixel sideways -- closes up the counters of 0, a and e once scaled, where a
face drawn bold keeps them open.

Only printable ASCII (0x20..0x7E) is emitted; the renderer substitutes '?'
for anything else.
"""
import gzip, struct, sys, pathlib

SRC = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/consolefonts/Lat15-TerminusBold16.psf.gz"
OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "font8x16.h"

raw = gzip.open(SRC, "rb").read() if SRC.endswith(".gz") else open(SRC, "rb").read()

if raw[:2] == b"\x36\x04":                       # PSF1
    charsize, off = raw[3], 4
elif raw[:4] == b"\x72\xb5\x4a\x86":             # PSF2
    _, hdrsize, _, _, charsize, height, width = struct.unpack("<7I", raw[4:32])
    assert width == 8, f"need an 8px-wide font, got {width}"
    off = hdrsize
else:
    sys.exit(f"{SRC}: not a PSF font")
assert charsize == 16, f"need a 16px-tall font, got {charsize}"

FIRST, LAST = 0x20, 0x7E
rows = []
for cp in range(FIRST, LAST + 1):
    g = raw[off + cp * charsize: off + (cp + 1) * charsize]
    rows.append("    { " + ", ".join(f"0x{b:02X}" for b in g) + f" }},  /* {chr(cp)!r} */")

OUT.write_text(f"""/* Generated by tools/make_font.py from {pathlib.Path(SRC).name} -- do not edit.
 *
 * Glyph data from Terminus Font, Copyright (c) 2010-2014 Dimitar Toshkov
 * Zhekov, with Reserved Font Name "Terminus Font". SIL Open Font License
 * 1.1 -- see licenses/OFL-1.1.txt and THIRD-PARTY.md.
 * Printable ASCII only; glyphs are 8 wide by 16 tall, one byte per row, MSB
 * leftmost.
 */
#pragma once

#include <stdint.h>

#define FONT_W     8
#define FONT_H     16
#define FONT_FIRST 0x{FIRST:02X}
#define FONT_LAST  0x{LAST:02X}

static const uint8_t font8x16[FONT_LAST - FONT_FIRST + 1][FONT_H] = {{
{chr(10).join(rows)}
}};
""")
print(f"wrote {OUT} ({LAST - FIRST + 1} glyphs)")
